<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cores\Ricebird.Clients\Ricebird.Clients.csproj" />
    <ProjectReference Include="..\..\Cores\Ricebird.Cms\Ricebird.Cms.csproj" />
    <ProjectReference Include="..\..\Cores\Ricebird.Configuration\Ricebird.Configuration.csproj" />
    <ProjectReference Include="..\..\Cores\Ricebird.Diagnostics\Ricebird.Diagnostics.csproj" />
    <ProjectReference Include="..\..\Cores\Ricebird.FileStorage\Ricebird.FileStorage.csproj" />
    <ProjectReference Include="..\..\Cores\Ricebird.Scedule\Ricebird.Scedules.csproj" />
    <ProjectReference Include="..\..\Cores\Ricebird.Security\Ricebird.Security.csproj" />
    <ProjectReference Include="..\..\Cores\Ricebird.ShortUrls\Ricebird.ShortUrls.csproj" />
    <ProjectReference Include="..\..\Cores\Ricebird.Sms\Ricebird.Sms.csproj" />
    <ProjectReference Include="..\..\Cores\Ricebird.Wechat\Ricebird.Wechat.csproj" />
    <ProjectReference Include="..\..\Modules\Ricebird.Misc\Ricebird.Misc.csproj" />
    <ProjectReference Include="..\..\Modules\Ricebird.Organizations\Ricebird.Organizations.csproj" />
    <ProjectReference Include="..\..\Ricebird.Framework\Ricebird.Framework.csproj" />
  </ItemGroup>

</Project>
